### ISSUE TITLE
Logo plataforma

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/paymentib#11]
Seguint l'estàndard dels altres projectes. En aquest s'hauria d'incloure el mateix logo i estructura de la capçalera que a Sistra2

Estat actual a PaymentIB
![image](https://user-images.githubusercontent.com/83401259/129336121-c6c0d504-560f-4ec1-b9eb-79c7f91e5d68.png)

Estat actual a Sistra2
![image](https://user-images.githubusercontent.com/83401259/129336199-0276d14e-182f-4c09-ba52-787318050e10.png)

**Comment by jsastre-dgtic** [comment]
S'afegirà per propertie una url del logo

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.1.3 (f09a54e)

**Comment by jparedes-indra** [comment]
Como se indica en el cuaderno de carga, para añadir un logo en la plataforma, en el archivo paymentib.properties en la ruta /app/caib/paymentib añadir la siguiente propiedad: 

back.logo="URL logo deseado" 

Así es como aparece cuando se añade un logo:
![image](https://user-images.githubusercontent.com/67064375/146512638-15232cb7-bf75-47a6-9616-2caaea9e4b2b.png)

**Comment by avillen-dgtic** [comment]
Hi ha incongruències entre els dos entorns. A PIB no tenim cap background com a S2.
![image](https://user-images.githubusercontent.com/83401259/146525878-eab42a3b-1ef9-4f13-92f2-514bfd85d98b.png)

![image](https://user-images.githubusercontent.com/83401259/146525679-b28c36b6-9124-484c-9ec2-357329d9a562.png)

**Comment by jparedes-indra** [comment]
Hemos actualizado la rama y el tag (b7e1c8b) de la última versión de PaymentIB para añadir el background.

**Comment by jsastre-dgtic** [comment]
Ok
![image](https://user-images.githubusercontent.com/18436867/147465961-6c369dfe-ff9d-43b0-b802-bae03fd58bc9.png)
