### ISSUE TITLE
Icones de l'entorn

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/paymentib#12]
A l'entorn de DEV, amb l'explorador amb català, ens trobem que la icona no canvia com si ho fa a Sistra2.

![image](https://user-images.githubusercontent.com/83401259/129336735-b1e1b08d-a442-4171-862a-a6a06daac8d4.png)

Entenc que a PRE i a PRO també passa el mateix. S'ha de tenir en compte l'idioma dels entorns.

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.1.3 (f09a54e)

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/146512328-0ccc7ba9-36d3-4d18-89f8-8337a9cb86ed.png)

**Comment by avillen-dgtic** [comment]
👍
