### ISSUE TITLE
No es mostra la versió de l'aplicació

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/paymentib#13]
Tenim el problema d'identificar la versió que està en marxa a tots els entorns
![image](https://user-images.githubusercontent.com/83401259/129337079-b1265091-f905-4b7a-888c-ba66efce548e.png)

Com als altres projectes caldria incloure el nombre de la versió.

**Comment by jsastre-dgtic** [comment]
Cal també normalitzar Desarrollo --> Desenvolupament

![image](https://user-images.githubusercontent.com/18436867/129352715-46ceceed-9069-490f-9559-6a2b4a951253.png)

**Comment by avillen-dgtic** [comment]
> Cal també normalitzar Desarrollo --> Desenvolupament
> 
> ![image](https://user-images.githubusercontent.com/18436867/129352715-46ceceed-9069-490f-9559-6a2b4a951253.png)

Aquesta issue ja ha estat creada
#12

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.1.3 (f09a54e)

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/146512137-f600fd89-c011-4135-9a2a-de83e7731e66.png)
![image](https://user-images.githubusercontent.com/67064375/146512145-d0d5caee-4445-477b-812e-2e0cdef254ef.png)

**Comment by avillen-dgtic** [comment]
👍
