### ISSUE TITLE
Identificació de l'usuari a la pantalla

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/paymentib#14]
A la pantalla es mostra la id de sessió de l'usuari i no les seves dades.

Estat actual a PaymentIB
![image](https://user-images.githubusercontent.com/83401259/129337349-f1549ba4-c9e7-46e4-b325-4d4af5958a39.png)

Estat actual a Sistra2
![image](https://user-images.githubusercontent.com/83401259/129337521-4a26513f-5783-46bf-b8ef-676716961370.png)

**Comment by jsastre-dgtic** [comment]
mancava la línia en negreta a l'standalone.xml:

<secure-deployment name="paymentibback.war">
                <realm>webdes</realm>
                <resource>goib-default</resource>
                <use-resource-role-mappings>false</use-resource-role-mappings>
                <public-client>true</public-client>
	     **<principal-attribute>preferred_username</principal-attribute>**
                <verify-token-audience>true</verify-token-audience>
            </secure-deployment>
Així ja surt:

![image](https://user-images.githubusercontent.com/18436867/131964669-51baeb6a-3535-4186-a925-7672a8aea2cd.png)
