### ISSUE TITLE
API interna que permeti consultar a Carpeta els pagaments d'un ciutadà i el seu estat. 

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/paymentib#15]
Podríem incloure el mètode de la recerca per DNI/Data que ja tenim implementat a paymentib als mètodes disponibles a l'API perquè Carpeta els pugui consultar i mostrar? 

![image](https://user-images.githubusercontent.com/18436867/152138262-07c05d3a-1389-4a4b-9f76-eaad9b6b29a0.png)

**Comment by jparedes-indra** [comment]
También haremos la búsqueda paginada, como en el resto de búsquedas.

**Comment by jcerdar-indra** [comment]
Se resuelve en el TAG 1.1.4 (17d24db)

**Comment by jcerdar-indra** [comment]
Se ha creado un nuevo método en el API de PaymentIB para consular los pagos. Para probar este método se puede hacer una llamada al método utilizando swagger-ui, con la siguiente URL: <dominio>/paymentibws/rest/swagger-ui.html

El método creado es el siguiente:
<img width="594" alt="image" src="https://user-images.githubusercontent.com/96287364/156995364-7994607b-e526-4829-8a5d-7802516d3341.png">
![image](https://user-images.githubusercontent.com/96287364/156995465-bc15ff4c-0ab6-4982-8190-e4e1f87e065f.png)
![image](https://user-images.githubusercontent.com/96287364/156995479-274d5bf6-1b15-46ce-9b25-5deca758b982.png)
