### ISSUE TITLE
Configurar mètodes pagament alternatius a nivell de tràmit

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/paymentib#18]
Configurar que un tràmit concret tengui un altre mètode de pagament creant una excepció a la regla general que marca el properties

**Comment by jsastre-dgtic** [comment]
Cal exemplificar TPV...

**Comment by jcerdar-indra** [comment]
Comentado en la https://github.com/GovernIB/sistra2/issues/540. Se ha enviado correo con propiedades para configurar TPV e importado TEST_PAGAMENT_TPV en el área de DEV para probarlo.
