### ISSUE TITLE
PIB: Generació justificant de pagament genèric

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/paymentib#2]

**Comment by rsanz-indra** [comment]
Se ha generado un justificante de pago basado en plantilla PDF
[JUSTIFICANTE_DE_PAGO_es.pdf](https://github.com/GovernIB/paymentib/files/2574913/JUSTIFICANTE_DE_PAGO_es.pdf)

**Comment by jsastre-dgtic** [comment]
manca formatar seguint el model GOIB (logo, tipografia...)

**Comment by jparedes-indra** [comment]
Se resuelve en la versión 1.1.3 (f09a54e)

**Comment by jparedes-indra** [comment]
![image](https://user-images.githubusercontent.com/67064375/146512814-2957ac9f-ee2a-4ce4-ae5e-3ae709245835.png)
