### ISSUE TITLE
Introduir les ajudes a la pantalla

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/paymentib#20]
Cal explicar què fa exactament verificar i confirmar.

**Comment by jparedes-indra** [comment]
Ahora aparecen las ayudas en la pantalla principal y en la del detalle de pago.

![image](https://user-images.githubusercontent.com/67064375/231986177-488491c4-89e6-4d69-a948-69d89549638c.png)

![image](https://user-images.githubusercontent.com/67064375/231986396-da115b9a-3f02-4184-af71-01d42ddd745f.png)

**Comment by avillen-dgtic** [comment]
👍
