### ISSUE TITLE
Incloure 2 rols nous a PIB

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/paymentib#22]
Actualment només tenim PIB_ADM.
Incloure PIB_CONS per tal de poder tenir usuaris de Consulta als Pagaments.

**Comment by jparedes-indra** [comment]
Ahora se muestra el rol del usuario y se puede intercambiar entre “Superadministrador” y “Consulta”.

![image](https://user-images.githubusercontent.com/67064375/231987264-6d6530ac-4558-40aa-a985-ddb6df4d5852.png)

**Comment by avillen-dgtic** [comment]
👍
