### ISSUE TITLE
Poder copiar qualsevol camp de les pantalles de PIB

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/paymentib#23]
Mateixa solució que a STG

![image](https://user-images.githubusercontent.com/18436867/213121680-689c1517-145a-442e-87fc-e1f7da178b15.png)

**Comment by jparedes-indra** [comment]
Se puede copiar cualquier texto y no se permite copiar zonas con varios elementos.

**Comment by jparedes-indra** [comment]
Se puede copiar cualquier texto con el menú contextual y no se permite copiar zonas con varios elementos.

**Comment by avillen-dgtic** [comment]
👍

**Comment by jparedes-indra** [comment]
Se ha detectado que en el dialog no aparece el menú contextual en los campos, pero si en las etiquetas... Procedemos a revisarlo.

![imagen](https://github.com/GovernIB/paymentib/assets/67064375/31b0edd1-2ebe-4720-9918-c49ea8d31035)

**Comment by avillen-dgtic** [comment]
👍
