### ISSUE TITLE
Millora al camp de Recerca 

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/paymentib#24]
Actualment, si introduim un espai després de PRO000017679_ no troba res. 

![image](https://user-images.githubusercontent.com/18436867/213168002-5358c0d0-8e5a-48be-8673-eda97a87ab60.png)

**Comment by jparedes-indra** [comment]
Ahora funciona correctamente la búsqueda aunque hayan espacios en blanco.

![image](https://user-images.githubusercontent.com/67064375/231989316-cdda4f70-9121-4828-b935-a47016fd93d6.png)

**Comment by avillen-dgtic** [comment]
El camp de recerca no funciona pels camps d'import i tampoc d'estat

**Comment by avillen-dgtic** [comment]
👍
