### ISSUE TITLE
Possibilitar ordenar per columnes. Per defecte ordenar per data de creació

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/paymentib#26]
![image](https://github.com/GovernIB/paymentib/assets/18436867/2e8dcf1a-15e6-41a8-be99-966d68550032)

**Comment by jparedes-indra** [comment]
Se puede ordenar por cualquier columna.

![imagen](https://github.com/GovernIB/paymentib/assets/67064375/69ad909a-8f2f-4c22-9790-dcf555ac6516)

**Comment by avillen-dgtic** [comment]
👍
