### ISSUE TITLE
Millores al Llistat de Pagaments

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/paymentib#27]
Es proposa passar les 3 columnes marcades a la imatge a la capçalera i amb desplegables, atès que per ara no es preveu que canviïn gaire els seus valors. Parlam d'Entitat, Passarel·la i Aplicació. 

També es proposa poder filtrar per localitzador ATIB afegint a la capçalera aquest camp. Així podríem verificar els pagaments fets directament des de la web de l'atib. Els presencials s'haurien de validar manualment amb el justificant del banc posant la data a ma. 

![image](https://github.com/GovernIB/paymentib/assets/18436867/d7ba198f-3555-4f2f-b266-4d8ff8875f68)

**Comment by jparedes-indra** [comment]
Se realizan todos los cambios solicitados.

![imagen](https://github.com/GovernIB/paymentib/assets/67064375/0dc3bab8-2976-4527-971b-2e34365ef903)

**Comment by avillen-dgtic** [comment]
👍
