### ISSUE TITLE
Possibilitat de filtrar segons mètode de pagament

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/paymentib#29]
si es permeten diferents mètodes de pagament (A IGOIB.IG_DGPL_PRV_CAT, per ecemple: DATOS_PAGO.setMetodosPago('TJ;BM;LC');), 

Hi hauria d'haver una manera de poder consultar quants pagaments s'han fet amb Bizum, o quants amb targeta?ATIB... ? 

![image](https://github.com/GovernIB/paymentib/assets/18436867/b21488c2-a3b9-47ae-a245-7fa5866902d3)

**Comment by jparedes-indra** [comment]
Se ha añadido una lista desplegable con los métodos de pago utilizados en los pagos registrados para filtrar y esa información, tanto en el listado como en el detalle.

![image](https://github.com/user-attachments/assets/21fc8cee-cae1-48f2-9569-2c3211cb6f8d)

**Comment by avillen-dgtic** [comment]
👍🏼
He canviat el mètode a un registre a DEV i filtra segons el mètode.
