### ISSUE TITLE
Traduir literal pàgina presentació html

### ISSUE THREAD

**Issue by jsastre-dgtic** [GovernIB/paymentib#30]
https://dev.caib.es/paymentibfront/seleccionEntidadPago.html

"Seleccioneu una entitat de pagament:"

![image](https://github.com/GovernIB/paymentib/assets/18436867/8493b728-29ad-4563-a1a3-df5e0afec71d)

**Comment by jparedes-indra** [comment]
Se visualiza el literal correctamente en catalán.

![image](https://github.com/user-attachments/assets/859605f6-186e-480b-893c-cd5c75b4e551)

**Comment by avillen-dgtic** [comment]
👍🏼 
![image](https://github.com/user-attachments/assets/33c81402-b5db-4cb4-b5b7-94db4217e6bf)
