### ISSUE TITLE
Actualització versió de Primefaces

### ISSUE THREAD

**Issue by dmadronal-indra** [GovernIB/paymentib#32]
Actualització versió de Primefaces a la darrera versió

**Comment by jsastre-dgtic** [comment]
Parlam de la v13?

**Comment by dmadronal-indra** [comment]
la actualización de primefaces se realizará a la ultima versión, actualmente la v14

**Comment by jparedes-indra** [comment]
Se actualiza la versión de PrimeFaces a la 14, como muestra el pom.xml del proyecto.

![image](https://github.com/user-attachments/assets/22a2e0b2-0892-4a4d-9343-c6c45d014ae5)

**Comment by avillen-dgtic** [comment]
👍🏼
