### ISSUE TITLE
Falla el Comportament de la Paginació

### ISSUE THREAD

**Issue by avillen-dgtic** [GovernIB/paymentib#33]
Només iniciar Paymentib, apareix la paginació amb un rang de pàgines que no correspon al nombre d'elements de la taula. I quan vols anar a una pàgina, dona error.

![image](https://github.com/user-attachments/assets/a93c97f4-e1c1-4a51-be31-4120600526f0)

![image](https://github.com/user-attachments/assets/bc0a6b87-6138-4372-a8a8-c0426ddf1a4d)

**Comment by jparedes-indra** [comment]
Se corrige el funcionamiento de la paginación y se resuelve el error.

![33PIBerrorPaginación](https://github.com/user-attachments/assets/b96f1157-6510-4843-bd29-6f99f30b8a03)

**Comment by avillen-dgtic** [comment]
l'error no es reprodueix però continua amb errades la paginació
![image](https://github.com/user-attachments/assets/2ed6510a-710d-42f1-b34b-4d8b9ca15cb1)

**Comment by avillen-dgtic** [comment]
La paginació funciona perfectament 👍🏼
