### ISSUE TITLE
TPV - Desenvolupament - Plugin passarel·la TPV: Notificador

### ISSUE THREAD

**Issue by jparedes-indra** [GovernIB/paymentib#5]

**Comment by jsastre-dgtic** [comment]
Després de finalitzar el desenvolupament de paymentib 1.1.0, s'actualitza el projecte en GitHub i es crea el TAG paymentib-1.1.0.
S'instal·la a DEV i s'elabora el quadern de càrrega per a passar a PRE i PRO.
